version: '3.2'
services:

  pop-health-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
      REACT_APP_START_YEAR: 2016
      DB_HOST: database
      DB_USER: "bulk-data-read-only-user"
      DB_PASS: "bulk-data-read-only-user-password"
      DB_SCHEMA: "bulk-data-stu-3"
      DB_WAIT_FOR_CONNECTION: "true"
      DB_CONNECTION_LIMIT: 10
      DB_QUEUE_LIMIT: 0
    depends_on:
      - database
    volumes:
      - "../server:/app/server"

  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./data:/var/lib/mysql"
      - "./dump:/docker-entrypoint-initdb.d"
