version: '3.2'
services:
  
  server:
    build:
      context: https://github.com/chb/pop-health-app-server.git
    ports:
      - "3003:3003"
    environment:
      HOST: "0.0.0.0"
      PORT: "3003"
      DB_HOST: database
      DB_USER: "bulk-data-read-only-user"
      DB_PASS: "bulk-data-read-only-user-password"
      DB_SCHEMA: "bulk-data-stu-3"
      DB_WAIT_FOR_CONNECTION: "true"
      DB_CONNECTION_LIMIT: 10
      DB_QUEUE_LIMIT: 0
      NO_SQL_AUTH: 1
    depends_on:
      - database

  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:80"
    environment:
      BACKEND_HOST: "0.0.0.0:3003"
      BACKEND_PATH: "/"
    depends_on:
      - server
      - database

  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./data:/var/lib/mysql"
      - "./dump:/docker-entrypoint-initdb.d"
